name: CI

on: [push]

jobs:
  test-cloud:
    name: Test on SCF Environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - nightly
          - 5.2.5
    container:
      image: stevapple/swift-scf:${{ matrix.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: swift test --enable-test-discovery

  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - bionic
          - focal
          - amazonlinux2
          - centos8
          - centos7
    container:
      image: swift:5.2.5-${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: swift test --enable-test-discovery

  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: swift test
